version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  lint:
    executor:
      name: node/default
    steps:
      - run: npm run eslint
  unit-test:
    executor:
      name: node/default
    steps:
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build
        - lint  
        - unit-test